#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdavnicaAutoDelova
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ProdavnicaAutoDelova")]
	public partial class ProdavnicaAutoDelovaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAutoDeo(AutoDeo instance);
    partial void UpdateAutoDeo(AutoDeo instance);
    partial void DeleteAutoDeo(AutoDeo instance);
    partial void InsertDobavljac(Dobavljac instance);
    partial void UpdateDobavljac(Dobavljac instance);
    partial void DeleteDobavljac(Dobavljac instance);
    partial void InsertKorisnik(Korisnik instance);
    partial void UpdateKorisnik(Korisnik instance);
    partial void DeleteKorisnik(Korisnik instance);
    partial void InsertMagacin(Magacin instance);
    partial void UpdateMagacin(Magacin instance);
    partial void DeleteMagacin(Magacin instance);
    partial void InsertRacun(Racun instance);
    partial void UpdateRacun(Racun instance);
    partial void DeleteRacun(Racun instance);
    partial void InsertStavkaRacuna(StavkaRacuna instance);
    partial void UpdateStavkaRacuna(StavkaRacuna instance);
    partial void DeleteStavkaRacuna(StavkaRacuna instance);
    #endregion
		
		public ProdavnicaAutoDelovaDataContext() : 
				base(global::ProdavnicaAutoDelova.Properties.Settings.Default.ProdavnicaAutoDelovaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ProdavnicaAutoDelovaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProdavnicaAutoDelovaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProdavnicaAutoDelovaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProdavnicaAutoDelovaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AutoDeo> AutoDeos
		{
			get
			{
				return this.GetTable<AutoDeo>();
			}
		}
		
		public System.Data.Linq.Table<Dobavljac> Dobavljacs
		{
			get
			{
				return this.GetTable<Dobavljac>();
			}
		}
		
		public System.Data.Linq.Table<Korisnik> Korisniks
		{
			get
			{
				return this.GetTable<Korisnik>();
			}
		}
		
		public System.Data.Linq.Table<Magacin> Magacins
		{
			get
			{
				return this.GetTable<Magacin>();
			}
		}
		
		public System.Data.Linq.Table<Racun> Racuns
		{
			get
			{
				return this.GetTable<Racun>();
			}
		}
		
		public System.Data.Linq.Table<StavkaRacuna> StavkaRacunas
		{
			get
			{
				return this.GetTable<StavkaRacuna>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AutoDeo")]
	public partial class AutoDeo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sifraAutoDela;
		
		private int _Cena;
		
		private string _Opis;
		
		private int _sifraDobavljaca;
		
		private EntitySet<Magacin> _Magacins;
		
		private EntitySet<StavkaRacuna> _StavkaRacunas;
		
		private EntityRef<Dobavljac> _Dobavljac;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsifraAutoDelaChanging(int value);
    partial void OnsifraAutoDelaChanged();
    partial void OnCenaChanging(int value);
    partial void OnCenaChanged();
    partial void OnOpisChanging(string value);
    partial void OnOpisChanged();
    partial void OnsifraDobavljacaChanging(int value);
    partial void OnsifraDobavljacaChanged();
    #endregion
		
		public AutoDeo()
		{
			this._Magacins = new EntitySet<Magacin>(new Action<Magacin>(this.attach_Magacins), new Action<Magacin>(this.detach_Magacins));
			this._StavkaRacunas = new EntitySet<StavkaRacuna>(new Action<StavkaRacuna>(this.attach_StavkaRacunas), new Action<StavkaRacuna>(this.detach_StavkaRacunas));
			this._Dobavljac = default(EntityRef<Dobavljac>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sifraAutoDela", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int sifraAutoDela
		{
			get
			{
				return this._sifraAutoDela;
			}
			set
			{
				if ((this._sifraAutoDela != value))
				{
					this.OnsifraAutoDelaChanging(value);
					this.SendPropertyChanging();
					this._sifraAutoDela = value;
					this.SendPropertyChanged("sifraAutoDela");
					this.OnsifraAutoDelaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cena", DbType="Int NOT NULL")]
		public int Cena
		{
			get
			{
				return this._Cena;
			}
			set
			{
				if ((this._Cena != value))
				{
					this.OnCenaChanging(value);
					this.SendPropertyChanging();
					this._Cena = value;
					this.SendPropertyChanged("Cena");
					this.OnCenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Opis", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Opis
		{
			get
			{
				return this._Opis;
			}
			set
			{
				if ((this._Opis != value))
				{
					this.OnOpisChanging(value);
					this.SendPropertyChanging();
					this._Opis = value;
					this.SendPropertyChanged("Opis");
					this.OnOpisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sifraDobavljaca", DbType="Int NOT NULL")]
		public int sifraDobavljaca
		{
			get
			{
				return this._sifraDobavljaca;
			}
			set
			{
				if ((this._sifraDobavljaca != value))
				{
					if (this._Dobavljac.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsifraDobavljacaChanging(value);
					this.SendPropertyChanging();
					this._sifraDobavljaca = value;
					this.SendPropertyChanged("sifraDobavljaca");
					this.OnsifraDobavljacaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AutoDeo_Magacin", Storage="_Magacins", ThisKey="sifraAutoDela", OtherKey="SifraAutoDela")]
		public EntitySet<Magacin> Magacins
		{
			get
			{
				return this._Magacins;
			}
			set
			{
				this._Magacins.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AutoDeo_StavkaRacuna", Storage="_StavkaRacunas", ThisKey="sifraAutoDela", OtherKey="SifraAutoDela")]
		public EntitySet<StavkaRacuna> StavkaRacunas
		{
			get
			{
				return this._StavkaRacunas;
			}
			set
			{
				this._StavkaRacunas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dobavljac_AutoDeo", Storage="_Dobavljac", ThisKey="sifraDobavljaca", OtherKey="sifraDobavljaca", IsForeignKey=true)]
		public Dobavljac Dobavljac
		{
			get
			{
				return this._Dobavljac.Entity;
			}
			set
			{
				Dobavljac previousValue = this._Dobavljac.Entity;
				if (((previousValue != value) 
							|| (this._Dobavljac.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Dobavljac.Entity = null;
						previousValue.AutoDeos.Remove(this);
					}
					this._Dobavljac.Entity = value;
					if ((value != null))
					{
						value.AutoDeos.Add(this);
						this._sifraDobavljaca = value.sifraDobavljaca;
					}
					else
					{
						this._sifraDobavljaca = default(int);
					}
					this.SendPropertyChanged("Dobavljac");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Magacins(Magacin entity)
		{
			this.SendPropertyChanging();
			entity.AutoDeo = this;
		}
		
		private void detach_Magacins(Magacin entity)
		{
			this.SendPropertyChanging();
			entity.AutoDeo = null;
		}
		
		private void attach_StavkaRacunas(StavkaRacuna entity)
		{
			this.SendPropertyChanging();
			entity.AutoDeo = this;
		}
		
		private void detach_StavkaRacunas(StavkaRacuna entity)
		{
			this.SendPropertyChanging();
			entity.AutoDeo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Dobavljac")]
	public partial class Dobavljac : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sifraDobavljaca;
		
		private string _nazivFirme;
		
		private string _brTelefona;
		
		private string _adresaDobavljaca;
		
		private EntitySet<AutoDeo> _AutoDeos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsifraDobavljacaChanging(int value);
    partial void OnsifraDobavljacaChanged();
    partial void OnnazivFirmeChanging(string value);
    partial void OnnazivFirmeChanged();
    partial void OnbrTelefonaChanging(string value);
    partial void OnbrTelefonaChanged();
    partial void OnadresaDobavljacaChanging(string value);
    partial void OnadresaDobavljacaChanged();
    #endregion
		
		public Dobavljac()
		{
			this._AutoDeos = new EntitySet<AutoDeo>(new Action<AutoDeo>(this.attach_AutoDeos), new Action<AutoDeo>(this.detach_AutoDeos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sifraDobavljaca", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int sifraDobavljaca
		{
			get
			{
				return this._sifraDobavljaca;
			}
			set
			{
				if ((this._sifraDobavljaca != value))
				{
					this.OnsifraDobavljacaChanging(value);
					this.SendPropertyChanging();
					this._sifraDobavljaca = value;
					this.SendPropertyChanged("sifraDobavljaca");
					this.OnsifraDobavljacaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazivFirme", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nazivFirme
		{
			get
			{
				return this._nazivFirme;
			}
			set
			{
				if ((this._nazivFirme != value))
				{
					this.OnnazivFirmeChanging(value);
					this.SendPropertyChanging();
					this._nazivFirme = value;
					this.SendPropertyChanged("nazivFirme");
					this.OnnazivFirmeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brTelefona", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string brTelefona
		{
			get
			{
				return this._brTelefona;
			}
			set
			{
				if ((this._brTelefona != value))
				{
					this.OnbrTelefonaChanging(value);
					this.SendPropertyChanging();
					this._brTelefona = value;
					this.SendPropertyChanged("brTelefona");
					this.OnbrTelefonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adresaDobavljaca", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string adresaDobavljaca
		{
			get
			{
				return this._adresaDobavljaca;
			}
			set
			{
				if ((this._adresaDobavljaca != value))
				{
					this.OnadresaDobavljacaChanging(value);
					this.SendPropertyChanging();
					this._adresaDobavljaca = value;
					this.SendPropertyChanged("adresaDobavljaca");
					this.OnadresaDobavljacaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dobavljac_AutoDeo", Storage="_AutoDeos", ThisKey="sifraDobavljaca", OtherKey="sifraDobavljaca")]
		public EntitySet<AutoDeo> AutoDeos
		{
			get
			{
				return this._AutoDeos;
			}
			set
			{
				this._AutoDeos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AutoDeos(AutoDeo entity)
		{
			this.SendPropertyChanging();
			entity.Dobavljac = this;
		}
		
		private void detach_AutoDeos(AutoDeo entity)
		{
			this.SendPropertyChanging();
			entity.Dobavljac = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Korisnik")]
	public partial class Korisnik : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _username;
		
		private string _password;
		
		private string _ime;
		
		private string _prezime;
		
		private string _email;
		
		private EntitySet<Racun> _Racuns;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnimeChanging(string value);
    partial void OnimeChanged();
    partial void OnprezimeChanging(string value);
    partial void OnprezimeChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public Korisnik()
		{
			this._Racuns = new EntitySet<Racun>(new Action<Racun>(this.attach_Racuns), new Action<Racun>(this.detach_Racuns));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ime", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ime
		{
			get
			{
				return this._ime;
			}
			set
			{
				if ((this._ime != value))
				{
					this.OnimeChanging(value);
					this.SendPropertyChanging();
					this._ime = value;
					this.SendPropertyChanged("ime");
					this.OnimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prezime", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string prezime
		{
			get
			{
				return this._prezime;
			}
			set
			{
				if ((this._prezime != value))
				{
					this.OnprezimeChanging(value);
					this.SendPropertyChanging();
					this._prezime = value;
					this.SendPropertyChanged("prezime");
					this.OnprezimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Korisnik_Racun", Storage="_Racuns", ThisKey="username", OtherKey="Korisnik")]
		public EntitySet<Racun> Racuns
		{
			get
			{
				return this._Racuns;
			}
			set
			{
				this._Racuns.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Racuns(Racun entity)
		{
			this.SendPropertyChanging();
			entity.Korisnik1 = this;
		}
		
		private void detach_Racuns(Racun entity)
		{
			this.SendPropertyChanging();
			entity.Korisnik1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Magacin")]
	public partial class Magacin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RedniBroj;
		
		private int _SifraAutoDela;
		
		private int _Kolicina;
		
		private EntityRef<AutoDeo> _AutoDeo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRedniBrojChanging(int value);
    partial void OnRedniBrojChanged();
    partial void OnSifraAutoDelaChanging(int value);
    partial void OnSifraAutoDelaChanged();
    partial void OnKolicinaChanging(int value);
    partial void OnKolicinaChanged();
    #endregion
		
		public Magacin()
		{
			this._AutoDeo = default(EntityRef<AutoDeo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RedniBroj", DbType="Int NOT NULL", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RedniBroj
		{
			get
			{
				return this._RedniBroj;
			}
			set
			{
				if ((this._RedniBroj != value))
				{
					this.OnRedniBrojChanging(value);
					this.SendPropertyChanging();
					this._RedniBroj = value;
					this.SendPropertyChanged("RedniBroj");
					this.OnRedniBrojChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SifraAutoDela", DbType="Int NOT NULL")]
		public int SifraAutoDela
		{
			get
			{
				return this._SifraAutoDela;
			}
			set
			{
				if ((this._SifraAutoDela != value))
				{
					if (this._AutoDeo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSifraAutoDelaChanging(value);
					this.SendPropertyChanging();
					this._SifraAutoDela = value;
					this.SendPropertyChanged("SifraAutoDela");
					this.OnSifraAutoDelaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kolicina", DbType="Int NOT NULL")]
		public int Kolicina
		{
			get
			{
				return this._Kolicina;
			}
			set
			{
				if ((this._Kolicina != value))
				{
					this.OnKolicinaChanging(value);
					this.SendPropertyChanging();
					this._Kolicina = value;
					this.SendPropertyChanged("Kolicina");
					this.OnKolicinaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AutoDeo_Magacin", Storage="_AutoDeo", ThisKey="SifraAutoDela", OtherKey="sifraAutoDela", IsForeignKey=true)]
		public AutoDeo AutoDeo
		{
			get
			{
				return this._AutoDeo.Entity;
			}
			set
			{
				AutoDeo previousValue = this._AutoDeo.Entity;
				if (((previousValue != value) 
							|| (this._AutoDeo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AutoDeo.Entity = null;
						previousValue.Magacins.Remove(this);
					}
					this._AutoDeo.Entity = value;
					if ((value != null))
					{
						value.Magacins.Add(this);
						this._SifraAutoDela = value.sifraAutoDela;
					}
					else
					{
						this._SifraAutoDela = default(int);
					}
					this.SendPropertyChanged("AutoDeo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Racun")]
	public partial class Racun : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SifraRacuna;
		
		private int _UkupnaVrednost;
		
		private System.DateTime _Date;
		
		private string _Korisnik;
		
		private EntitySet<StavkaRacuna> _StavkaRacunas;
		
		private EntityRef<Korisnik> _Korisnik1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSifraRacunaChanging(int value);
    partial void OnSifraRacunaChanged();
    partial void OnUkupnaVrednostChanging(int value);
    partial void OnUkupnaVrednostChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnKorisnikChanging(string value);
    partial void OnKorisnikChanged();
    #endregion
		
		public Racun()
		{
			this._StavkaRacunas = new EntitySet<StavkaRacuna>(new Action<StavkaRacuna>(this.attach_StavkaRacunas), new Action<StavkaRacuna>(this.detach_StavkaRacunas));
			this._Korisnik1 = default(EntityRef<Korisnik>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SifraRacuna", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SifraRacuna
		{
			get
			{
				return this._SifraRacuna;
			}
			set
			{
				if ((this._SifraRacuna != value))
				{
					this.OnSifraRacunaChanging(value);
					this.SendPropertyChanging();
					this._SifraRacuna = value;
					this.SendPropertyChanged("SifraRacuna");
					this.OnSifraRacunaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UkupnaVrednost", DbType="Int NOT NULL")]
		public int UkupnaVrednost
		{
			get
			{
				return this._UkupnaVrednost;
			}
			set
			{
				if ((this._UkupnaVrednost != value))
				{
					this.OnUkupnaVrednostChanging(value);
					this.SendPropertyChanging();
					this._UkupnaVrednost = value;
					this.SendPropertyChanged("UkupnaVrednost");
					this.OnUkupnaVrednostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Korisnik", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Korisnik
		{
			get
			{
				return this._Korisnik;
			}
			set
			{
				if ((this._Korisnik != value))
				{
					if (this._Korisnik1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKorisnikChanging(value);
					this.SendPropertyChanging();
					this._Korisnik = value;
					this.SendPropertyChanged("Korisnik");
					this.OnKorisnikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Racun_StavkaRacuna", Storage="_StavkaRacunas", ThisKey="SifraRacuna", OtherKey="SifraRacuna")]
		public EntitySet<StavkaRacuna> StavkaRacunas
		{
			get
			{
				return this._StavkaRacunas;
			}
			set
			{
				this._StavkaRacunas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Korisnik_Racun", Storage="_Korisnik1", ThisKey="Korisnik", OtherKey="username", IsForeignKey=true)]
		public Korisnik Korisnik1
		{
			get
			{
				return this._Korisnik1.Entity;
			}
			set
			{
				Korisnik previousValue = this._Korisnik1.Entity;
				if (((previousValue != value) 
							|| (this._Korisnik1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Korisnik1.Entity = null;
						previousValue.Racuns.Remove(this);
					}
					this._Korisnik1.Entity = value;
					if ((value != null))
					{
						value.Racuns.Add(this);
						this._Korisnik = value.username;
					}
					else
					{
						this._Korisnik = default(string);
					}
					this.SendPropertyChanged("Korisnik1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_StavkaRacunas(StavkaRacuna entity)
		{
			this.SendPropertyChanging();
			entity.Racun = this;
		}
		
		private void detach_StavkaRacunas(StavkaRacuna entity)
		{
			this.SendPropertyChanging();
			entity.Racun = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StavkaRacuna")]
	public partial class StavkaRacuna : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SifraRacuna;
		
		private int _RedniBroj;
		
		private int _SifraAutoDela;
		
		private int _Kolicina;
		
		private int _Vrednost;
		
		private EntityRef<AutoDeo> _AutoDeo;
		
		private EntityRef<Racun> _Racun;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSifraRacunaChanging(int value);
    partial void OnSifraRacunaChanged();
    partial void OnRedniBrojChanging(int value);
    partial void OnRedniBrojChanged();
    partial void OnSifraAutoDelaChanging(int value);
    partial void OnSifraAutoDelaChanged();
    partial void OnKolicinaChanging(int value);
    partial void OnKolicinaChanged();
    partial void OnVrednostChanging(int value);
    partial void OnVrednostChanged();
    #endregion
		
		public StavkaRacuna()
		{
			this._AutoDeo = default(EntityRef<AutoDeo>);
			this._Racun = default(EntityRef<Racun>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SifraRacuna", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SifraRacuna
		{
			get
			{
				return this._SifraRacuna;
			}
			set
			{
				if ((this._SifraRacuna != value))
				{
					if (this._Racun.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSifraRacunaChanging(value);
					this.SendPropertyChanging();
					this._SifraRacuna = value;
					this.SendPropertyChanged("SifraRacuna");
					this.OnSifraRacunaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RedniBroj", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int RedniBroj
		{
			get
			{
				return this._RedniBroj;
			}
			set
			{
				if ((this._RedniBroj != value))
				{
					this.OnRedniBrojChanging(value);
					this.SendPropertyChanging();
					this._RedniBroj = value;
					this.SendPropertyChanged("RedniBroj");
					this.OnRedniBrojChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SifraAutoDela", DbType="Int NOT NULL")]
		public int SifraAutoDela
		{
			get
			{
				return this._SifraAutoDela;
			}
			set
			{
				if ((this._SifraAutoDela != value))
				{
					if (this._AutoDeo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSifraAutoDelaChanging(value);
					this.SendPropertyChanging();
					this._SifraAutoDela = value;
					this.SendPropertyChanged("SifraAutoDela");
					this.OnSifraAutoDelaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kolicina", DbType="Int NOT NULL")]
		public int Kolicina
		{
			get
			{
				return this._Kolicina;
			}
			set
			{
				if ((this._Kolicina != value))
				{
					this.OnKolicinaChanging(value);
					this.SendPropertyChanging();
					this._Kolicina = value;
					this.SendPropertyChanged("Kolicina");
					this.OnKolicinaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vrednost", DbType="Int NOT NULL")]
		public int Vrednost
		{
			get
			{
				return this._Vrednost;
			}
			set
			{
				if ((this._Vrednost != value))
				{
					this.OnVrednostChanging(value);
					this.SendPropertyChanging();
					this._Vrednost = value;
					this.SendPropertyChanged("Vrednost");
					this.OnVrednostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AutoDeo_StavkaRacuna", Storage="_AutoDeo", ThisKey="SifraAutoDela", OtherKey="sifraAutoDela", IsForeignKey=true)]
		public AutoDeo AutoDeo
		{
			get
			{
				return this._AutoDeo.Entity;
			}
			set
			{
				AutoDeo previousValue = this._AutoDeo.Entity;
				if (((previousValue != value) 
							|| (this._AutoDeo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AutoDeo.Entity = null;
						previousValue.StavkaRacunas.Remove(this);
					}
					this._AutoDeo.Entity = value;
					if ((value != null))
					{
						value.StavkaRacunas.Add(this);
						this._SifraAutoDela = value.sifraAutoDela;
					}
					else
					{
						this._SifraAutoDela = default(int);
					}
					this.SendPropertyChanged("AutoDeo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Racun_StavkaRacuna", Storage="_Racun", ThisKey="SifraRacuna", OtherKey="SifraRacuna", IsForeignKey=true)]
		public Racun Racun
		{
			get
			{
				return this._Racun.Entity;
			}
			set
			{
				Racun previousValue = this._Racun.Entity;
				if (((previousValue != value) 
							|| (this._Racun.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Racun.Entity = null;
						previousValue.StavkaRacunas.Remove(this);
					}
					this._Racun.Entity = value;
					if ((value != null))
					{
						value.StavkaRacunas.Add(this);
						this._SifraRacuna = value.SifraRacuna;
					}
					else
					{
						this._SifraRacuna = default(int);
					}
					this.SendPropertyChanged("Racun");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
